export class ToolParameter {
  constructor({ name, type, description, required = true, default: defaultValue = null }) {
    this.name = name;
    this.type = type;
    this.description = description;
    this.required = required;
    this.default = defaultValue;
  }

  toDict() {
    return {
      name: this.name,
      type: this.type,
      description: this.description,
      required: this.required,
      default: this.default,
    };
  }
}

export function toolAction(name = null, description = null) {
  return function (target, propertyKey, descriptor) {
    descriptor.value._isToolAction = true;
    descriptor.value._toolName = name;
    descriptor.value._toolDescription = description;
    return descriptor;
  };
}

export class Tool {
  constructor({ name, description, expandable = false }) {
    this.name = name;
    this.description = description;
    this.expandable = expandable;
  }

  async run(parameters) {
    throw new Error(`${this.constructor.name} must implement run()`);
  }

  getParameters() {
    throw new Error(`${this.constructor.name} must implement getParameters()`);
  }

  getExpandedTools() {
    if (!this.expandable) return null;

    const tools = [];
    const proto = Object.getPrototypeOf(this);
    for (const key of Object.getOwnPropertyNames(proto)) {
      if (key === 'constructor') continue;
      const method = this[key];
      if (typeof method === 'function' && method._isToolAction) {
        const tool = new AutoGeneratedTool({
          parent: this,
          method,
          methodName: key,
          name: method._toolName,
          description: method._toolDescription,
        });
        tools.push(tool);
      }
    }
    return tools.length > 0 ? tools : null;
  }

  validateParameters(parameters) {
    const requiredParams = this.getParameters().filter(p => p.required);
    return requiredParams.every(p => p.name in parameters);
  }

  toDict() {
    return {
      name: this.name,
      description: this.description,
      parameters: this.getParameters().map(p => p.toDict()),
    };
  }

  toOpenAISchema() {
    const parameters = this.getParameters();
    const properties = {};
    const required = [];

    for (const param of parameters) {
      const prop = { type: param.type, description: param.description };
      if (param.default !== null) {
        prop.description = `${param.description} (默认: ${param.default})`;
      }
      if (param.type === 'array') {
        prop.items = { type: 'string' };
      }
      properties[param.name] = prop;
      if (param.required) required.push(param.name);
    }

    return {
      type: 'function',
      function: {
        name: this.name,
        description: this.description,
        parameters: {
          type: 'object',
          properties,
          required,
        },
      },
    };
  }

  toString() {
    return `Tool(name=${this.name})`;
  }
}

export class AutoGeneratedTool extends Tool {
  constructor({ parent, method, methodName, name = null, description = null }) {
    const toolName = name || `${parent.name}_${methodName.replace(/^_/, '')}`;
    const toolDesc = description || `执行 ${methodName}`;
    super({ name: toolName, description: toolDesc });

    this.parent = parent;
    this.method = method;
    this._parameters = this._parseParameters(method, methodName);
  }

  _parseParameters(method, methodName) {
    const fnStr = method.toString();
    const paramMatch = fnStr.match(/\(([^)]*)\)/);
    if (!paramMatch) return [];

    const paramStr = paramMatch[1].trim();
    if (!paramStr) return [];

    const params = [];
    const paramParts = paramStr.split(',').map(p => p.trim());

    for (const part of paramParts) {
      if (!part || part.startsWith('...')) continue;
      const [name, defaultValueRaw] = part.split('=').map(s => s.trim());
      const required = !defaultValueRaw;
      const defaultValue = defaultValueRaw ? this._parseDefaultValue(defaultValueRaw) : null;
      let type = 'string';
      if (defaultValue !== null) {
        if (typeof defaultValue === 'number') type = 'number';
        else if (typeof defaultValue === 'boolean') type = 'boolean';
        else if (Array.isArray(defaultValue)) type = 'array';
        else if (typeof defaultValue === 'object') type = 'object';
      }
      params.push(new ToolParameter({
        name,
        type,
        description: `参数 ${name}`,
        required,
        default: required ? null : defaultValue,
      }));
    }

    return params;
  }

  _parseDefaultValue(raw) {
    raw = raw.trim();
    if (raw === 'null' || raw === 'undefined') return null;
    if (raw === 'true') return true;
    if (raw === 'false') return false;
    const num = Number(raw);
    if (!isNaN(num)) return num;
    if ((raw.startsWith('"') && raw.endsWith('"')) || (raw.startsWith("'") && raw.endsWith("'"))) {
      return raw.slice(1, -1);
    }
    if (raw.startsWith('[')) {
      try { return JSON.parse(raw); } catch { return []; }
    }
    return raw;
  }

  getParameters() {
    return this._parameters;
  }

  async run(parameters) {
    return await this.method.call(this.parent, parameters);
  }
}